# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

APP_NAME = "Runner"

platform :ios do
  desc "Description of what the lane does"
  lane :tf_chargeme do
    api_key = app_store_connect_api_key(
      key_id: "C9K9NBPS6M",
      issuer_id: "e76dc971-c9ea-454d-b857-c15ecfcf4d35",
      key_filepath: "./AuthKey_C9K9NBPS6M.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    increment_build_number

    gym(
      scheme: "#{APP_NAME}",
      configuration: "TestFlight",
      output_name: "#{APP_NAME}_TestFlight.ipa",
      export_method: "app-store",
      export_options:{
        signingStyle: "manual",
        provisioningProfiles: {
            "com.chargeme": "ChargeMe profile"
        }
      },
      silent: false
    )
    changelog = "Fixes"
    pilot(
      api_key: api_key,
      beta_app_description: "ChargeMe beta",
      distribute_external: true,
      changelog: changelog
      skip_waiting_for_build_processing: true
      groups: ["External testers"]
    )
  end
end
